version: '3'

services:
  db:
    container_name: db
    image: postgres:latest
    ports:
      - "3011:3011"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGPORT: 3011
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=postgres --dbname=postgres"]
      interval: 2s
      timeout: 2s
      retries: 6

  backend:
    container_name: backend
    # image: redouansammour/buzzloop-backend:latest
    build: 
      context: ./backend
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "3010:3010"
    depends_on:
      db:
        condition: service_healthy
    
  frontend:
    # image: redouansammour/buzzloop-frontend:latest
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  api-gateway:
    container_name: api-gateway2
    image: nginx:latest
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Corrected path
    depends_on:
      - backend

      