version: "3.8"
name: buzzloop-dev

services:
  db:
    container_name: db
    image: postgres:latest
    ports:
      - 3011:3011
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGPORT: 3011
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=postgres --dbname=postgres"]
      interval: 5s
      timeout: 5s
      retries: 6

  frontend:
    container_name: frontend-buzzloop
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - 3010:3010
    depends_on:
      - db
    
  api-gateway:
    container_name: api-gateway2
    image: nginx:latest
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

